### ISSUE TITLE
Can't log in after 28.11.2024

### ISSUE THREAD

**Issue by Moskus** [ToreKjaer/volkswagen-weconnect#2]
It throws the error "Failed to get code" in `VwConnection.cs`:
```
		string text = PostPasswordForm(openIdConfig, formContent, clientId, actionUrl, refererUrl);
		if (!text.Contains("code="))
		{
			throw new InvalidOperationException("Failed to get code");
		}
```

**Comment by soad-boon** [comment]
Try logging in via the myVolkswagen website. If this happens then there is a popup that something has changed(terms & conditions, etc), which you need to accept. Should be working fine again afterwards.

**Comment by Moskus** [comment]
I did get a terms and condition change alert, but I get it each time I log in, so the code still fails on the same location.

I'll test again later, perhaps my acceptance of the new terms and conditions hasn't propagated throught the WeConnect system yet.

I should use [https://myvolkswagen.net](myvolkswagen.net), right?

**Comment by gulars** [comment]
@Moskus 
Tip, go to  WeConnect website, choose a random country, and then back again to yours. Next time login you do not get the popup :-)

**Comment by Moskus** [comment]
@gulars, I'd love to give this a try, but when I go to mywvolksvagen.net, it auto-transfers me to the Norwegian site! I can't select another country other than "Norge" in the disabled drop down list.

![image](https://github.com/user-attachments/assets/faf012a7-09d3-49ed-9b1f-645b3b54fe14)

**Comment by gulars** [comment]
@Moskus you need to do it after login, then next time you will not be asked:
![image](https://github.com/user-attachments/assets/50423310-6494-43aa-8572-6a29e42d2657)

**Comment by Moskus** [comment]
I'm still getting this. The privacy statements is already set on under Account Settings -> Privacy.

**Comment by ToreKjaer** [comment]
I just had a similar issue. Going to [this URL](https://identity.vwgroup.io/oidc/v1/authorize?client_id=a24fba63-34b3-4d43-b181-942111e6bda8@apps_vw-dilab_com&scope=openid%20profile%20badge%20cars%20dealers%20vin&response_type=code&redirect_uri=weconnect://authenticated) and logging in I was presented with a bunch of terms I needed to consent to. After that I was able to successfully login using this library.
